app/Http/routes.php
Route::post('root/country/generateSlug','superadmin\CountryController@generateSlug');

Route::resource('root/state','superadmin\StateController');
Route::resource('root/state/delete','superadmin\StateController@delete');
Route::resource('root/state/changeStatus','superadmin\StateController@changeStatus');
Route::post('root/state/generateSlug','superadmin\StateController@generateSlug');

Route::resource('root/city','superadmin\CityController');
Route::resource('root/city/delete','superadmin\CityController@delete');
Route::resource('root/city/changeStatus','superadmin\CityController@changeStatus');
Route::post('root/city/generateSlug','superadmin\CityController@generateSlug');

Route::resource('root/zipcode','superadmin\ZipcodeController');
Route::resource('root/zipcode/delete','superadmin\ZipcodeController@delete');
Route::resource('root/zipcode/changeStatus','superadmin\ZipcodeController@changeStatus');

Route::resource('root/faqcat','superadmin\FaqCategoryController');
Route::resource('root/faqcat/delete','superadmin\FaqCategoryController@delete');
Route::resource('root/faqcat/changeStatus','superadmin\FaqCategoryController@changeStatus');

Route::resource('root/faq','superadmin\FaqQuestionController');
Route::resource('root/faq/delete','superadmin\FaqQuestionController@delete');
Route::resource('root/faq/changeStatus','superadmin\FaqQuestionController@changeStatus');

Route::resource('root/infopage','superadmin\FrontPageController');
Route::resource('root/infopage/delete','superadmin\FrontPageController@delete');
Route::resource('root/infopage/changeStatus','superadmin\FrontPageController@changeStatus');

Route::resource('root/marketingtips','superadmin\MarketingTipController');
Route::resource('root/marketingtips/delete','superadmin\MarketingTipController@delete');
Route::resource('root/marketingtips/changeStatus','superadmin\MarketingTipController@changeStatus');

Route::resource('root/countryfrontlist','superadmin\FrontCountryController');

Route::resource('root/statefrontlist','superadmin\FrontStateController');

Route::resource('root/cityfrontlist','superadmin\FrontCityController');

Route::resource('root/kitchenfrontlist','superadmin\FrontKitchenController');

Route::resource('root/sociallinks','superadmin\SocialNetworkController');

Route::resource('root/livefeed','superadmin\LiveFeedController');

Route::resource('root/searchfilter','superadmin\RestSearchFilterController');
Route::resource('root/searchfilter/changeStatus','superadmin\RestSearchFilterController@changeStatus');
//Route::resource('/register','front\RegistrationController@register');
//Route::resource('/register/verifyemail/{code}','front\RegistrationController@verifyemail');
Route::resource('/get_zipcodes','front\HomeController@get_zipcodes');

Route::get('/search','front\RestSearchController@index');
Route::post('/search','front\RestSearchController@index');
Route::post('/userfav','front\RestSearchController@user_favourite');
Route::post('/checkzip','front\RestSearchController@check_zip');
Route::post('/checkzip_new','front\RestSearchController@checkzip_new');


//Nikhil's Code ends----------------------------------------------------------------------------------------------------

////////////////////////Start kishan's routing////////////////////////

      /////////////////Start Superadmin Routing///////////////////

Route::resource('root/restaurant','superadmin\RestaurantController'); //20_04_2016
Route::resource('root/kitchenmap','superadmin\KitchenMapController'); //28_04_2016
Route::resource('ajax/getkitchen','superadmin\AjaxController@getkitchen'); //30_04_2016
Route::resource('ajax/getRootCategory','superadmin\AjaxController@getRootCategory'); //02_05_2016
Route::resource('ajax/gatData','superadmin\AjaxController@getData'); //02_05_2016
Route::resource('root/rootcatmap','superadmin\RootCategoryMapController'); //02_05_2016
Route::resource('root/category','superadmin\CategoryController'); //02_05_2016

Route::resource('ajax/getExistValue','superadmin\AjaxController@getExistValue'); //06_05_2016
Route::resource('ajax/deleteItems','superadmin\AjaxController@deleteItems'); //09_05_2016
Route::resource('root/menu','superadmin\MenuController'); //09_05_2016
Route::resource('ajax/getCatKitchenPriceType','superadmin\AjaxController@getCatKitchenPriceType'); //09_05_2016
Route::resource('root/submenu','superadmin\SubMenuController'); //11_05_2016
Route::resource('ajax/gatDataSingleTable','superadmin\AjaxController@gatDataSingleTable'); //11_05_2016
Route::resource('root/extratypemap','superadmin\RestExtraTypeMapController'); //13_05_2016
Route::resource('ajax/getExtraType','superadmin\AjaxController@getExtraType'); //13_05_2016
Route::resource('root/extramap','superadmin\RestExtraMapController'); //13_05_2016
Route::resource('ajax/deleteRestaurants','superadmin\AjaxController@deleteRestaurants'); //19_05_2016
Route::resource('root/restsetting','superadmin\RestaurantSettingController'); //19_05_2016
Route::resource('ajax/gatPriceType','superadmin\AjaxController@gatPriceType'); //27_05_2016
Route::resource('cart/addcart','front\FrontCartController@addItem'); //03_06_2016
Route::post('registercart','Auth\FrontAuthController@registerCartUser');

     /////////////////End Superadmin Routing///////////////////

   /////////////////Start Front Routing///////////////////

Route::resource('restaurant/{restId}/search','front\RestaurantDetailController@getDetails');
Route::resource('restaurant/{restId}/review-order','front\FrontCartController@reviewOrder');
Route::resource('restaurant/{restId}/shipping-area','front\FrontCartController@shippingArea');
Route::resource('front/ajax/getExistValOneCond','front\FrontCartController@getExistValOneCond');
Route::resource('front/ajax/getAddress','front\FrontAjaxController@getAddress');
Route::resource('front/ajax/setAddress','front\FrontAjaxController@setAddress');
Route::resource('front/ajax/deleteAddress','front\FrontAjaxController@deleteAddress');
// Route::post('checkout','front\FrontCartController@cartCheckout');
Route::post('checkout','front\FrontCartController@place_order');

Route::resource('deleteAddress','front\FrontCartController@deleteAddress');
Route::resource('front/ajax/setTimePreOrder','front\FrontAjaxController@setTimePreOrder');
Route::resource('front/ajax/checkCouponCode','front\FrontAjaxController@checkCouponCode');    
Route::get('confirm-order/{id}','front\FrontCartController@orderConfirmation');

//Nikhil's-------------------------------------------------
Route::resource('check-order-status','front\FrontCartController@check_order_status');
Route::get('live-route/{id}','front\FrontCartController@live_route');
Route::GET('front/order/payment','front\FrontCartController@payment');
////////////////End Front Routing///////////////////

////////////////////////End kishan's routing////////////////////////


//------------------------------------------Start Routing by vikas---------------------------------------
Route::resource('root/categories','superadmin\RootcatergoriesController');
Route::post('root/categories/delete', 'superadmin\RootcatergoriesController@delete');
Route::resource('root/kitchen','superadmin\KitchenController');
Route::post('root/kitchens/delete', 'superadmin\KitchenController@delete');
Route::post('root/kitchens/fetchdata','superadmin\KitchenController@fetchdata');
Route::post('root/kitchens/update/{kitchen_id}','superadmin\KitchenController@update');
Route::resource('root/alergic-contents','superadmin\AlergicController');
Route::post('root/alergic_contents/delete', 'superadmin\AlergicController@delete');
Route::resource('root/colors','superadmin\ColorController');
Route::post('root/colors/delete', 'superadmin\ColorController@delete');
Route::resource('root/day-time','superadmin\DaytimeController');
Route::resource('root/day/time/search','superadmin\DaytimeController@search');
Route::GET('root/day/time/add-time/{restaurant_id}','superadmin\DaytimeController@create');
Route::resource('root/pages','superadmin\PageController');
Route::post('root/pages/delete', 'superadmin\PageController@delete');
Route::resource('root/email-types','superadmin\EmailtypeController');
Route::post('root/email_types/delete', 'superadmin\EmailtypeController@delete');
Route::resource('root/currency','superadmin\CurrencyController');
Route::post('root/currency/delete', 'superadmin\CurrencyController@delete');
Route::resource('root/pricetypes','superadmin\PriceTypeController');
Route::post('root/pricetypes/delete', 'superadmin\PriceTypeController@delete');

Route::resource('root/services','superadmin\ServiceController');
Route::post('root/services/delete', 'superadmin\ServiceController@delete');
Route::resource('root/menus/categories','superadmin\MenuCategoryController');
Route::post('root/menus/categories/delete', 'superadmin\MenuCategoryController@delete');
Route::resource('root/tax/setting','superadmin\TaxSettingController');
Route::post('root/tax/setting/delete', 'superadmin\TaxSettingController@delete');

Route::resource('root/metrics','superadmin\MetricsController');
Route::post('root/metrics/delete', 'superadmin\MetricsController@delete');
Route::resource('root/shop/categories','superadmin\ShopCategoryController');
Route::post('root/shop/categories/delete', 'superadmin\ShopCategoryController@delete');
Route::resource('root/shop/metricscatmap','superadmin\ShopMetricCategoryController'); 
Route::resource('shop/metricscatmap/getdata','superadmin\ShopMetricCategoryController@getdata');
Route::resource('root/shop/items','superadmin\ShopItemController');
Route::post('root/shop/items/delete', 'superadmin\ShopItemController@delete');
Route::resource('root/item/detail/{item_id}/{category_id}/search','superadmin\ShopItemController@search');
Route::resource('root/shop/inventory','superadmin\ShopInventoryController');
Route::post('root/shop/inventory/getCatItems','superadmin\ShopInventoryController@getCatItems');
Route::post('root/shop/inventory/delete', 'superadmin\ShopInventoryController@delete');

resources/views/superadmin/restaurants/submenu/create.blade.php
@extends('layouts.superadminbody')

@section('title')
@endsection


@section('body')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Sub Menu
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{url('root/dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
         <li><a href="{{route('root.submenu.index')}}"><i class="fa fa-dashboard"></i> Restaurant Management</a></li>
        <li class="active">Add Sub Menu</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
        
        
          <!-- Custom tabs (Charts with tabs)-->
          <div class="box">
            <div class="box-header">
            </div>
            <!-- /.box-header -->
			   <div class="box-body">
            {{--    Error Display--}}
             @if($errors->any())
				<div class="alert alert-danger ">
					<ul class="list-unstyled">
						@foreach($errors->all() as $error)
							<li> {{ $error }}</li>
						@endforeach
					</ul>
				</div>
			 @endif
                {{--    Error Display ends--}}

                @if(Session::has('category_error'))
				<div class="alert alert-danger " style="padding: 7px 15px;">
				  {{ Session::get('category_error') }}
				  {{ Session::put('category_error','') }}
				</div>
			    @endif
            
            <div class="panel panel-primary theme-border">
                    <div class="panel-heading theme-bg">
                       
                        <h4 id="contactLabel" class="panel-title"><span class="glyphicon glyphicon-plus"></span> Add New Sub Menu.</h4>
                    </div>
                    
                     <div style="padding: 5px;" class="modal-body">
                     <div class="panel-body">
                     {!! Form::open(array('route'=>'root.submenu.store','id'=>'submenu-form','files'=>true)) !!}
                     
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
										{!! Form::label('', 'Restaurant Name', array('class' => '"control-label')) !!}<span class="red">*</span>
										
											<select class="form-control js-example-basic-multiple" id="restro-id" name="restro_name" onchange="getDataSingleTable(this.value,'rest_menus','id','name','rest_detail_id','menu')">

											<option value="">Select</option>
											@foreach($restro_names as $restro_name)
											<option value="{{$restro_name->id}}">{{$restro_name->f_name}} {{$restro_name->l_name}}</option>
											@endforeach

											</select>
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
										{!! Form::label('', 'Menu Name', array('class' => '"control-label')) !!}<span class="red">*</span>
										
											<select class="form-control" name="menu_name" id="menu">

											
											</select>
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
										{!! Form::label('', 'Name', array('class' => '"control-label')) !!}<span class="red">*</span>
										
											{!! Form :: text('submenu_name','',['placeholder'=>'Enter Sub Menu Name','class'=>'form-control','id'=>'sub-menu'])  !!}

										</div>

									</div>

                  <div class="col-md-6">
                    <div class="form-group">
                    {!! Form::label('', 'Short Name', array('class' => '"control-label')) !!}
                    
                      {!! Form :: text('shortname','',['placeholder'=>'Enter Short Name','class'=>'form-control','id'=>'sub-menu'])  !!}
                    </div>

                  </div>

                  <div class="col-md-6">
                    <div class="form-group">
                    {!! Form::label('', 'Code', array('class' => '"control-label')) !!}
                    
                      {!! Form :: text('code','',['placeholder'=>'Enter Code','class'=>'form-control','id'=>'sub-menu'])  !!}
                    </div>

                  </div>
									<div class="col-md-6">	
										<div class="form-group">
										{!! Form::label('', 'Image', array('class' => '"control-label')) !!}
										
											<input class="form-control" type="file" name="file" style="border: none; font-size: 12px; padding: 0px;">
										</div>
									</div>
									
									
									<div class="col-md-6">
										<div class="form-group">
										<label class="&quot;control-label" for="">Description</label>

										{!! Form :: textarea('description','',['placeholder'=>'Enter Description','class'=>'form-control','id'=>'description'])  !!}
											<!-- <textarea class="form-control"> </textarea> -->
										</div>
									</div>

                  <div class="col-md-6">
                    <div class="form-group">
                    {!! Form::label('', 'Info', array('class' => '"control-label')) !!}
                    
                      {!! Form :: text('info','',['placeholder'=>'Enter Information','class'=>'form-control','id'=>'sub-menu'])  !!}
                    </div>

                  </div>

                  <div class="col-md-6">
                    <div class="form-group">
                    {!! Form::label('', 'Priority', array('class' => '"control-label')) !!}<span class="red">*</span>
                    
                      {!! Form :: text('priority','',['placeholder'=>'Enter Priority','class'=>'form-control','id'=>'priority'])  !!}
                    </div>

                  </div>

                                    <div id="have-submenu">
                                        <div class="col-md-12">
                                            <div class="form-group" id="price-type">




                                            </div>
                                        </div>

                                        <div class="col-md-12">
                                            <div class="form-group">


                                                <label class="checkbox">{!! Form :: checkbox('alergic',1,'',['class'=>'alergic-check','id'=>'alergic-check','onclick'=>'showValueOnCheckbox("alergic-check","alergic-contents")'])  !!}
                                                    <span><strong>Is Alergic</strong></span>
                                                </label>

                                                <div class="row" id="alergic-contents" style="display:none;">
                                                    @foreach($alergic_contents as $alergic_content)
                                                        <div class="col-md-3">
                                                            <label class="checkbox">{!! Form :: checkbox('alergic_contents[]',$alergic_content->id) !!}<span>{{$alergic_content->name}}</span></label>
                                                        </div>
                                                    @endforeach

                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-12">
                                            <div class="form-group">


                                                <label class="checkbox">{!! Form :: checkbox('spicy',1,'',['class'=>'spicy-check','id'=>'spicy-check','onclick'=>'showValueOnCheckbox("spicy-check","spicy-contents")'])  !!}
                                                    <span><strong>Is Spicy</strong></span>
                                                </label>

                                                <div class="row" id="spicy-contents" style="display:none;">
                                                    @foreach($spices as $spice)
                                                        <div class="col-md-3">
                                                            <label class="checkbox">{!! Form :: checkbox('spicy_content[]',$spice->id) !!}<span>{{$spice->name}}</span></label>
                                                        </div>
                                                    @endforeach


                                                </div>
                                            </div>
                                        </div>
                                    </div>

								</div>

								<div class="form-group margin-top">
							<hr>
							<input type="submit" value="Add" name="submit" class="btn btn-primary pull-right" onclick='checkExistingValue("cat-name","restro-id","rest_categories","name","rest_detail_id","cat-exist-error","This category is already exist for this restaurant","")'>
								
									<!-- <button class="btn  btn-primary" type="button"><i class="fa fa-plus"></i> Add </button> -->
									
									<p><span class="red">*</span> - Required Fields.</p>
								</div>
								{!! Form :: close() !!}
								
							<!-- </form> -->
						</div>
                     
                     </div>  
                      
                    </div>
			</div>
            <!-- /.box-body -->
          </div>
         
          <!-- quick email widget -->
          

        </section>
        <!-- /.Left col -->
        <!-- right col (We are only adding the ID to make the widgets sortable)-->
        
        <!-- right col -->
      </div>
      <!-- /.row (main row) -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
 
@endsection

@section('script')
     <script type="text/javascript"> 
     $(document).ready(function(){
     $("#submenu-form").validate({
      rules: {


        restro_name: {
            required: true
               },
         menu_name: {
            required: true
               },
         submenu_name: {
            required: true
               },
          info: {
              required: true
          },
          'price_types[]': {
              required: true,
              number: true
          },
         priority: {
            required: true,
             number: true
            
               }
         
         
        },
       messages: {
                    restro_name: "Please select restaurant",
                    menu_name: "Please select menu name",
                    submenu_name: "Please enter submenu name",
                    info: "Please enter some information",
                    priority: "Please enter priority"
                    
                },
         
     });


         $("#restro-id").change(function(){

             var restroId=$("#restro-id").val();

             var token=$("#token-value").val();

             $.ajax({
                 url: base_url+'/ajax/gatPriceType',
                 type: "POST",
                 dataType:"json",
                 data: {'restId':restroId,'_token':token},

                 success: function (data) {

                     if(data.priceTypesItem=='' || data.priceTypesItem==null){
                         var priceType='';

                     }
                     else{
                         var priceType=data.priceTypesSpan+data.priceTypesItem;

                     }

                     $('#price-type').html(priceType);

                 },
                 error: function (jqXHR, textStatus, errorThrown) {

                 }
             });
         });

});
    </script>

   
    @endsection

resources/views/superadmin/restaurants/submenu/index.blade.php
@extends('layouts.superadminbody')

@section('title')
@endsection


@section('body')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Sub Menu
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{url('root/dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
         <li><a href="{{route('root.submenu.index')}}"><i class="fa fa-dashboard"></i> Restaurant Management</a></li>
        <li class="active">Sub Menu List</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
        
        
          <!-- Custom tabs (Charts with tabs)-->
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
		     
			<div class="col-md-8 form-group">
            {!! Form::open(array('route'=>'root.submenu.index','class'=>'form-horizontal','method'=>'GET')) !!}
            
               
                 <label class="col-sm-2 control-label">Restaurant Name</label>
                 <div class="col-sm-4">
               
                   <select class="form-control js-example-basic-multiple" name="restaurant">
                   <option value="">Select</option>

                   @foreach($restro_names as $restro_name)

                   @if($restro_name->id==$restro_detail_id)
                   <option value="{{$restro_name->id}}" selected >{{$restro_name->f_name}} {{$restro_name->l_name}}</option>
                   @else
                   <option value="{{$restro_name->id}}" >{{$restro_name->f_name}} {{$restro_name->l_name}}</option>
                   @endif
                   @endforeach
                   </select>

                 </div>
               
                 <div class="col-sm-4">
                   <button class="btn btn-primary" type="submit">Get Details</button>
                   <a class="btn btn-primary" href="{{url('root/submenu/')}}">Reset Search</a>
                 </div>
                
               
               {!! Form::close() !!}
            <!-- /.box-header -->
            </div>
             <div class="col-sm-4 text-right" style="margin-bottom:10px;"> <div class="btn-group">
			 <a class="btn btn-default" href="{{route('root.submenu.create')}}"><span>Add</span></a><a class="btn btn-default DTTT_button_print" id="ToolTables_simpledatatable_4" title="View print view" tabindex="0" aria-controls="simpledatatable" onclick="window.print()"><span>Print</span></a>
			 <a class="btn btn-default DTTT_button_print" onclick="download_submenu()"  id="ToolTables_simpledatatable_4" title="View print view" tabindex="0" aria-controls="simpledatatable"><span>Download</span></a>

             <a class="btn btn-danger DTTT_button_xls" id="ToolTables_simpledatatable_2" tabindex="0" aria-controls="simpledatatable" onclick="delete_items('submenu_class','sub_menus','rest_sub_menus')"><span>Delete</span></a></div></div>

            <div class="clearfix" style="margin: 20px 0;"></div>
            <div class="box-body">
			@if(Session::has('message'))
				<div class="alert alert-success" style="padding: 7px 15px;">
				  {{ Session::get('message') }}
				  {{ Session::put('message','') }}
				</div>
			@endif
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                 <th>
                            <div class="checkbox icheck">
                                <label>
                                {!! Form::checkbox('selectAll','',null,['id'=>'selectAll','class'=>'selectAll','onclick'=>'SelectDeselectAllCheckbox()']) !!}
                                <span class=""></span>
                                </label>
                            </div>
                        </th>
                  <th>Restaurant</th>
                  <th>Menu Name</th>
                  <th>Submenu Name</th>
                  <th>Code</th>
                  <th>Status</th>
                   <th>Action</th>
                </tr>
                </thead>
                <tbody>
                
              @foreach($getRestroSubMenus as $getRestroSubMenu)
              <tr>
                <td><div class="checkbox icheck">
                  <label>
                   <!--  <input type="checkbox"> <span> </span> -->
                    {!! Form::checkbox('sub_menus', $getRestroSubMenu->id, null, ['class' => 'submenu_class checkBoxClass']) !!}<span></span>
                  </label>
                </div></td>
                <td>{{$getRestroSubMenu->getResturant->f_name}} {{$getRestroSubMenu->getResturant->l_name}}</td>
                <td>@if($getRestroSubMenu->getMenu){{$getRestroSubMenu->getMenu->name}} @else {{''}} @endif</td>
                <td>{{$getRestroSubMenu->name}}</td>
                <td>{{$getRestroSubMenu->code}}</td>
                  <td>@if($getRestroSubMenu->status=='1')
                          Active
                      @elseif($getRestroSubMenu->status=='0')
                          Inactive
                      @endif
                  </td>
                
                <td>
                <a href="{{URL :: asset('root/submenu/'.$getRestroSubMenu->id)}}/edit" class="btn btn-success"><i class="fa fa-edit"></i></a>
                </td>
              </tr>
              
              @endforeach
              
                </tbody>
                {!! $getRestroSubMenus->appends(['restaurant'=>$restro_detail_id])->render() !!}
              </table>
              
               		
            </div>
            <!-- /.box-body -->
          </div>
         
          <!-- quick email widget -->
          

        </section>
        <!-- /.Left col -->
        <!-- right col (We are only adding the ID to make the widgets sortable)-->
        
        <!-- right col -->
      </div>
      <!-- /.row (main row) -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  

  
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!--added by Rajlakshmi(31-05-16)-->
	<div id="download" style="display:none;" >
	</div>
<!--added by Rajlakshmi(31-05-16)-->

@endsection

@section('script')
<script>
/*added by Rajlakshmi(31-05-16)*/
		function download_submenu(){
            var len = $(".submenu_class:checked").length;
            if(len==0){
                alert('Please select atleast one Submenu');
                return false;
            }

            var r = confirm("Are you sure to download the selected Submenu.?");
            if (r == true) {
                var selectedPages = new Array();
                $('input:checkbox[name="sub_menus"]:checked').each(function(){
                    selectedPages.push($(this).val());
                });
                $.ajax({
                    url: '{{url('root/submenu/download')}}',
                    type: "post",
                    dataType:"json",
                    data: {'selectedSubmenus':selectedPages, "_token":"{{ csrf_token() }}"},
                    success: function(res){
                   
                     
                    
                      $("#download").html(res.data1);
					 
                        var doc = new jsPDF('p', 'pt');
						var elem = document.getElementById("table1");
						var res = doc.autoTableHtmlToJson(elem);
						doc.autoTable(res.columns, res.data);
					    doc.save("submenu_list.pdf");
				}
            });
        } else {
            return false;
        }
	   }
	 
/*added by Rajlakshmi(31-05-16)*/
</script>
@endsection