app/Http/routes.php
Route::post('root/country/generateSlug','superadmin\CountryController@generateSlug');

Route::resource('root/state','superadmin\StateController');
Route::resource('root/state/delete','superadmin\StateController@delete');
Route::resource('root/state/changeStatus','superadmin\StateController@changeStatus');
Route::post('root/state/generateSlug','superadmin\StateController@generateSlug');

Route::resource('root/city','superadmin\CityController');
Route::resource('root/city/delete','superadmin\CityController@delete');
Route::resource('root/city/changeStatus','superadmin\CityController@changeStatus');
Route::post('root/city/generateSlug','superadmin\CityController@generateSlug');

Route::resource('root/zipcode','superadmin\ZipcodeController');
Route::resource('root/zipcode/delete','superadmin\ZipcodeController@delete');
Route::resource('root/zipcode/changeStatus','superadmin\ZipcodeController@changeStatus');

Route::resource('root/faqcat','superadmin\FaqCategoryController');
Route::resource('root/faqcat/delete','superadmin\FaqCategoryController@delete');
Route::resource('root/faqcat/changeStatus','superadmin\FaqCategoryController@changeStatus');

Route::resource('root/faq','superadmin\FaqQuestionController');
Route::resource('root/faq/delete','superadmin\FaqQuestionController@delete');
Route::resource('root/faq/changeStatus','superadmin\FaqQuestionController@changeStatus');

Route::resource('root/infopage','superadmin\FrontPageController');
Route::resource('root/infopage/delete','superadmin\FrontPageController@delete');
Route::resource('root/infopage/changeStatus','superadmin\FrontPageController@changeStatus');

Route::resource('root/marketingtips','superadmin\MarketingTipController');
Route::resource('root/marketingtips/delete','superadmin\MarketingTipController@delete');
Route::resource('root/marketingtips/changeStatus','superadmin\MarketingTipController@changeStatus');

Route::resource('root/countryfrontlist','superadmin\FrontCountryController');

Route::resource('root/statefrontlist','superadmin\FrontStateController');

Route::resource('root/cityfrontlist','superadmin\FrontCityController');

Route::resource('root/kitchenfrontlist','superadmin\FrontKitchenController');

Route::resource('root/sociallinks','superadmin\SocialNetworkController');

Route::resource('root/livefeed','superadmin\LiveFeedController');

Route::resource('root/searchfilter','superadmin\RestSearchFilterController');
Route::resource('root/searchfilter/changeStatus','superadmin\RestSearchFilterController@changeStatus');
//Route::resource('/register','front\RegistrationController@register');
//Route::resource('/register/verifyemail/{code}','front\RegistrationController@verifyemail');
Route::resource('/get_zipcodes','front\HomeController@get_zipcodes');

Route::get('/search','front\RestSearchController@index');
Route::post('/search','front\RestSearchController@index');
Route::post('/userfav','front\RestSearchController@user_favourite');
Route::post('/checkzip','front\RestSearchController@check_zip');
Route::post('/checkzip_new','front\RestSearchController@checkzip_new');


//Nikhil's Code ends----------------------------------------------------------------------------------------------------

////////////////////////Start kishan's routing////////////////////////

      /////////////////Start Superadmin Routing///////////////////

Route::resource('root/restaurant','superadmin\RestaurantController'); //20_04_2016
Route::resource('root/kitchenmap','superadmin\KitchenMapController'); //28_04_2016
Route::resource('ajax/getkitchen','superadmin\AjaxController@getkitchen'); //30_04_2016
Route::resource('ajax/getRootCategory','superadmin\AjaxController@getRootCategory'); //02_05_2016
Route::resource('ajax/gatData','superadmin\AjaxController@getData'); //02_05_2016
Route::resource('root/rootcatmap','superadmin\RootCategoryMapController'); //02_05_2016
Route::resource('root/category','superadmin\CategoryController'); //02_05_2016

Route::resource('ajax/getExistValue','superadmin\AjaxController@getExistValue'); //06_05_2016
Route::resource('ajax/deleteItems','superadmin\AjaxController@deleteItems'); //09_05_2016
Route::resource('root/menu','superadmin\MenuController'); //09_05_2016
Route::resource('ajax/getCatKitchenPriceType','superadmin\AjaxController@getCatKitchenPriceType'); //09_05_2016
Route::resource('root/submenu','superadmin\SubMenuController'); //11_05_2016
Route::resource('ajax/gatDataSingleTable','superadmin\AjaxController@gatDataSingleTable'); //11_05_2016
Route::resource('root/extratypemap','superadmin\RestExtraTypeMapController'); //13_05_2016
Route::resource('ajax/getExtraType','superadmin\AjaxController@getExtraType'); //13_05_2016
Route::resource('root/extramap','superadmin\RestExtraMapController'); //13_05_2016
Route::resource('ajax/deleteRestaurants','superadmin\AjaxController@deleteRestaurants'); //19_05_2016
Route::resource('root/restsetting','superadmin\RestaurantSettingController'); //19_05_2016
Route::resource('ajax/gatPriceType','superadmin\AjaxController@gatPriceType'); //27_05_2016
Route::resource('cart/addcart','front\FrontCartController@addItem'); //03_06_2016
Route::post('registercart','Auth\FrontAuthController@registerCartUser');

     /////////////////End Superadmin Routing///////////////////

   /////////////////Start Front Routing///////////////////

Route::resource('restaurant/{restId}/search','front\RestaurantDetailController@getDetails');
Route::resource('restaurant/{restId}/review-order','front\FrontCartController@reviewOrder');
Route::resource('restaurant/{restId}/shipping-area','front\FrontCartController@shippingArea');
Route::resource('front/ajax/getExistValOneCond','front\FrontCartController@getExistValOneCond');
Route::resource('front/ajax/getAddress','front\FrontAjaxController@getAddress');
Route::resource('front/ajax/setAddress','front\FrontAjaxController@setAddress');
Route::resource('front/ajax/deleteAddress','front\FrontAjaxController@deleteAddress');
// Route::post('checkout','front\FrontCartController@cartCheckout');
Route::post('checkout','front\FrontCartController@place_order');

Route::resource('deleteAddress','front\FrontCartController@deleteAddress');
Route::resource('front/ajax/setTimePreOrder','front\FrontAjaxController@setTimePreOrder');
Route::resource('front/ajax/checkCouponCode','front\FrontAjaxController@checkCouponCode');    
Route::get('confirm-order/{id}','front\FrontCartController@orderConfirmation');

//Nikhil's-------------------------------------------------
Route::resource('check-order-status','front\FrontCartController@check_order_status');
Route::get('live-route/{id}','front\FrontCartController@live_route');
Route::GET('front/order/payment','front\FrontCartController@payment');
////////////////End Front Routing///////////////////

////////////////////////End kishan's routing////////////////////////


//------------------------------------------Start Routing by vikas---------------------------------------
Route::resource('root/categories','superadmin\RootcatergoriesController');
Route::post('root/categories/delete', 'superadmin\RootcatergoriesController@delete');
Route::resource('root/kitchen','superadmin\KitchenController');
Route::post('root/kitchens/delete', 'superadmin\KitchenController@delete');
Route::post('root/kitchens/fetchdata','superadmin\KitchenController@fetchdata');
Route::post('root/kitchens/update/{kitchen_id}','superadmin\KitchenController@update');
Route::resource('root/alergic-contents','superadmin\AlergicController');
Route::post('root/alergic_contents/delete', 'superadmin\AlergicController@delete');
Route::resource('root/colors','superadmin\ColorController');
Route::post('root/colors/delete', 'superadmin\ColorController@delete');
Route::resource('root/day-time','superadmin\DaytimeController');
Route::resource('root/day/time/search','superadmin\DaytimeController@search');
Route::GET('root/day/time/add-time/{restaurant_id}','superadmin\DaytimeController@create');
Route::resource('root/pages','superadmin\PageController');
Route::post('root/pages/delete', 'superadmin\PageController@delete');
Route::resource('root/email-types','superadmin\EmailtypeController');
Route::post('root/email_types/delete', 'superadmin\EmailtypeController@delete');
Route::resource('root/currency','superadmin\CurrencyController');
Route::post('root/currency/delete', 'superadmin\CurrencyController@delete');
Route::resource('root/pricetypes','superadmin\PriceTypeController');
Route::post('root/pricetypes/delete', 'superadmin\PriceTypeController@delete');

Route::resource('root/services','superadmin\ServiceController');
Route::post('root/services/delete', 'superadmin\ServiceController@delete');
Route::resource('root/menus/categories','superadmin\MenuCategoryController');
Route::post('root/menus/categories/delete', 'superadmin\MenuCategoryController@delete');
Route::resource('root/tax/setting','superadmin\TaxSettingController');
Route::post('root/tax/setting/delete', 'superadmin\TaxSettingController@delete');

Route::resource('root/metrics','superadmin\MetricsController');
Route::post('root/metrics/delete', 'superadmin\MetricsController@delete');
Route::resource('root/shop/categories','superadmin\ShopCategoryController');
Route::post('root/shop/categories/delete', 'superadmin\ShopCategoryController@delete');
Route::resource('root/shop/metricscatmap','superadmin\ShopMetricCategoryController'); 
Route::resource('shop/metricscatmap/getdata','superadmin\ShopMetricCategoryController@getdata');
Route::resource('root/shop/items','superadmin\ShopItemController');
Route::post('root/shop/items/delete', 'superadmin\ShopItemController@delete');
Route::resource('root/item/detail/{item_id}/{category_id}/search','superadmin\ShopItemController@search');
Route::resource('root/shop/inventory','superadmin\ShopInventoryController');
Route::post('root/shop/inventory/getCatItems','superadmin\ShopInventoryController@getCatItems');
Route::post('root/shop/inventory/delete', 'superadmin\ShopInventoryController@delete');

resources/views/superadmin/restaurants/extras_map/create.blade.php
@extends('layouts.superadminbody')

@section('title')
@endsection


@section('body')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Extras
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{url('root/dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
         <li><a href="{{route('root.extramap.index')}}"><i class="fa fa-dashboard"></i> Restaurant Management</a></li>
        <li class="active">Add Extras</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
        
        
          <!-- Custom tabs (Charts with tabs)-->
          <div class="box">
            <div class="box-header">
            </div>
            <!-- /.box-header -->

            @if($errors->any())
                    <div class="alert alert-danger ">
                        <ul class="list-unstyled">
                            @foreach($errors->all() as $error)
                                <li> {{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
            @endif

            
            
            <div class="panel panel-primary theme-border">
                    <div class="panel-heading theme-bg">
                       
                        <h4 class="panel-title" id="contactLabel"><span class="glyphicon glyphicon-plus"></span> Add New Extras </h4>
                    </div>
                    
                     <div class="modal-body" style="padding: 5px;">
                     <div class="panel-body">
						 {!! Form::open(array('route'=>'root.extramap.create','id'=>'searchingForm','class'=>'form-horizontal','method'=>'GET')) !!}
						 {{--<form class="form-horizontal">--}}
							 <div class="col-md-12 form-group">
								 <label class="col-sm-2 control-label">Restaurant Name<span class="red">*</span></label>
								 <div class="col-sm-4">
                 @if($restro_detail_id)
									 <select class="form-control" disabled name="restaurant">
                   @else
                   <select class="form-control js-example-basic-multiple" name="restaurant" id="restaurant" onChange="hideErrorMsg('restauranterr')">
                   @endif
                   <option value="">Select</option>

                   @foreach($restro_names as $restro_name)

                   @if($restro_name->id==$restro_detail_id)
                   <option value="{{$restro_name->id}}" selected >{{$restro_name->f_name}} {{$restro_name->l_name}}</option>
                   @else
                   <option value="{{$restro_name->id}}" >{{$restro_name->f_name}} {{$restro_name->l_name}}</option>
                   @endif
                   @endforeach
                   </select>
                   <span id="restauranterr" class="text-danger"></span>

								 </div>
                 @if(!$restro_detail_id)
								 <div class="col-sm-4">
									 <button class="btn btn-primary" type="button" onclick="validate_rest()">Get Extra Types</button>
								 </div>
                 @endif
							 </div>
               <div class="clearfix"></div>
               {!! Form::close() !!}
							 
               @if($restro_detail_id)
               <div>
                {!! Form::open(array('route'=>'root.extramap.store','class'=>'form-horizontal', 'id'=> 'serviceform')) !!}
							 <hr>
							 <div class="col-md-12 form-group">
								 <label class="col-sm-2 control-label">&nbsp;</label>
								 <div class="col-sm-9">

                 <?php $i=1; ?>
                 @if(count($extraTypeMaps)>0)
                   @foreach($extraTypeMaps as $extraTypeMap)

                   <li>{{$extraTypeMap->name}}
                   <input type="hidden" name="extra_type<?php echo $i; ?>" value="{{$extraTypeMap->id}}">

                   <ul>
                  
                   @foreach(App\superadmin\MenuExtra::extraType($extraTypeMap->id) as $data)
                     
                     @if(in_array($data['id'],$extrasMaps))
                     <input type="checkbox" class="extraTypes" name="extras<?php echo $i; ?>[]" value="{{$data['id']}}" checked>{{$data['name']}}
                     @else
                    <input type="checkbox" class="extraTypes" name="extras<?php echo $i; ?>[]" value="{{$data['id']}}" >{{$data['name']}}
                     @endif
                     
                      
                      
                      @endforeach
                   </ul>
                   </li>

									<?php $i++ ?>
                   @endforeach
                   @else
                         <span>No Record Found</span>
                     @endif

                   {!! Form :: hidden('restaurant',$restro_detail_id,['id'=>'restro-detail-id'])  !!}

                   {!! Form :: hidden('total_value',$i,['id'=>''])  !!}

								 </div>
							 </div>
                                                         <span id="serviceerr" class="text-danger" ></span>
							 <div class="col-md-12 form-group">
								 <label class="col-sm-2 control-label"></label>
								 <div class="col-sm-4">
								 @if(count($extraTypeMaps)>0)
                                    <button class="btn btn-primary" type="button"  onclick="validate_service()">Submit</button>
                                    @endif
                                     <a class="btn btn-primary" href="{{url('root/extramap/create/')}}">Cancel</a>
								 </div>
							 </div>
						  {!! Form::close() !!}
              </div>
              @endif
							<!-- </form> -->
						</div>
                     
                     </div>  
                    </div>
            <!-- /.box-body -->
          </div>
          <!-- quick email widget -->
        </section>
        <!-- /.Left col -->
        <!-- right col (We are only adding the ID to make the widgets sortable)-->
        
        <!-- right col -->
      </div>
      <!-- /.row (main row) -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
 
@endsection

@section('script')
<script>
    function hideErrorMsg(id){
        $('#'+id).attr('style', 'display:none');
    }
    function validate_rest()
    {
        $restaurant = $('#restaurant').val();
        if($restaurant=='')
        {
            $("#restaurant").focus();
            $("#restauranterr").html('Please select a restaurant');
            $("#restauranterr").show();
            return false;
        }
        document.forms["searchingForm"].submit();
    }
    function validate_service()
    {
        var len = $(".extraTypes:checked").length;
        if(len==0){
            $("#serviceerr").html('Please check atleast one Extra');
            $("#serviceerr").show();
            return false;
        }
        document.forms["serviceform"].submit();
    }
</script>
@endsection

resources/views/superadmin/restaurants/extras_map/index.blade.php
@extends('layouts.superadminbody')

@section('title')
@endsection


@section('body')


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Extras
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{url('root/dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
         <li><a href="{{route('root.extramap.index')}}"><i class="fa fa-dashboard"></i> Restaurant Management</a></li>
        <li class="active">Extras</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      
      <!-- /.row -->
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
        
        
          <!-- Custom tabs (Charts with tabs)-->
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            

            <div class="col-sm-8 text-left" style="margin-bottom:10px;">
                {!! Form::open(array('url'=>"root/extramap/",'class'=>'form-inline','method'=>'GET')) !!}
                    {!! Form::text('search',$search,["id"=>'search','style'=>'width:50%',"class"=>"form-control","placeholder"=>"Search"]) !!}
                    {!! Form::submit('Search',['id'=>'submit','class'=>'btn btn-primary']) !!}
                    <a class="btn btn-primary" href="{{url('root/extramap/')}}">Reset Search</a>
                {!! Form::close() !!}
            </div>
            
             <div class="col-sm-4 text-right" style="margin-bottom:10px;"> <div class="btn-group"><a class="btn btn-default" href="{{route('root.extramap.create')}}"><span>Assign Extras</span></a>


             <!-- <a class="btn btn-default DTTT_button_csv"  data-toggle="modal" data-target="#edit-form" data-original-title><span>Edit</span></a><a class="btn btn-default DTTT_button_print" id="ToolTables_simpledatatable_4" title="View print view" tabindex="0" aria-controls="simpledatatable"><span>Print</span></a><a class="btn btn-default DTTT_button_print" id="ToolTables_simpledatatable_4" title="View print view" tabindex="0" aria-controls="simpledatatable"><span>Download</span></a><a class="btn btn-danger DTTT_button_xls" id="ToolTables_simpledatatable_2" tabindex="0" aria-controls="simpledatatable"><span>Delete</span></a> --></div></div>
            
            <?php 
                $class='<i class="fa fa-caret-down text-muted"></i>';
                $class1='<i class="fa fa-caret-up text-muted"></i>';
                $class2='<i class="fa fa-sort text-muted"></i>';
            ?>
            
            <div class="clearfix" style="margin: 20px 0;"></div>
            
            <div class="box-body">
			@if(Session::has('message'))
                    <div class="alert alert-success" style="padding: 7px 15px;">
					  {{ Session::get('message') }}
					  {{ Session::put('message','') }}
                    </div>
                @endif
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                <th>S No.</th>
                <th>
                    <a href="{{url('root/extramap/')}}?search=<?=(($search!='') ? $search :'')?>&type=<?=$type=='name' ? 'name-desc' :'name';?>">
                    Restaurant
                    <?php if($type=='name'){ echo $class; } elseif($type=='name-desc'){ echo $class1; } else { echo $class2; } ?>
                    </a>
                </th>
                  <th>Views</th>
                </tr>
                </thead>
                <tbody>
               
              
                <?php $i=$pages['from']; ?>
                  @foreach($restro_names as $restro_name)
                        <tr>
                            <td><?php echo $i; ?></td>
                            
                            <td>{{$restro_name->f_name}} {{$restro_name->l_name}}</td>

                         	<?php $restroName=$restro_name['f_name'].' '.$restro_name['l_name'] ?>

                           <td>{!! Html::link('#','View Assigned Extras',array('id' => 'restro-kitchen','onclick'=>'show_modal("extra-type-view",'.$restro_name->id.',"extra-type-list","restro-name","'.$restroName.'")'), true) !!}

                           		</td>

                           {!! Form :: hidden('restaurant',$restroName ,['id'=>'restro-names'])  !!}
                          

                        </tr>
                        <?php $i++; ?>
                 @endforeach
              
               
              
                </tbody> 
                
              </table>
            {!! $restro_names->appends(Request::except('page'))->render() !!}
               		
            </div>
            <!-- /.box-body -->
          </div>
         
          <!-- quick email widget -->
          

        </section>
        <!-- /.Left col -->
        <!-- right col (We are only adding the ID to make the widgets sortable)-->
        
        <!-- right col -->
      </div>
      <!-- /.row (main row) -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  

  
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->



<div class="modal fade" id="extra-type-view" tabindex="-1" role="dialog" aria-labelledby="contactLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="panel panel-primary theme-border">
                    <div class="panel-heading theme-bg">
                   
                    <span id="restro-name">hello</span>
                   
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

                    </div>
                   				<div class="panel-body">
                   				<div class="row PopupPublished" id="extra-type-list">
                   					

               					</div>
                   				</div>

                    </div>
                </div>
            </div>



<script>
function show_modal(formId,restro_id,appendId,restroNameId,restroName) {

	$.ajax({

		url: '{{ url('ajax/getExtraType') }}',
        type: "POST",
        data: {'restro_detail_id':restro_id, '_token': '{{ csrf_token() }}'},
        
	    success: function (data) {
		    //alert(data);
		    if(data=='' || data==null){
		    	data='No extra type assigned';
		    }
		    else{
		    	data=data;
		    }
			document.getElementById(appendId).innerHTML = data;
      document.getElementById(restroNameId).innerHTML = restroName;
			
		},
	    error: function (jqXHR, textStatus, errorThrown) {
	      
	    }
	});
	
	$("#"+formId).modal('show');

}


</script>

@endsection